site_name: "Inland Consequences"
site_url: 

theme:
  name: readthedocs

plugins:
  - search
  - include-markdown
  - macros

repo_url: https://github.com/fema-ffrd/inland-consequences

nav:
  - Overview:
    - index.md
  - Methodlogy:
    - inventory_methodology.md
    - buildingvalidation_techapproach.md
    - hazardvalidation_techapproach.md
    - inland_methodology.md
    - coastal_methodology.md

  - Technical Implementation:
    - building_inventories.md
    - ddf_tech_implementation.md
    - AAL_tech_implementation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - javascripts/katex.js