site_name: "Inland Consequences"
site_url: 

theme:
  name: readthedocs

plugins:
  - search
  - include-markdown
  - macros

repo_url: https://github.com/fema-ffrd/inland-consequences

nav:
  - Overview:
    - index.md
  - Methodlogy:
    - inventory_methodology.md
  - Technical Implementation:
    - building_inventories.md