site_name: "Inland Consequences"
site_url: 

theme:
  name: readthedocs

plugins:
  - search
  - include-markdown
  - macros

repo_url: https://github.com/fema-ffrd/inland-consequences

nav:
  - Overview:
    - index.md
    - tasks.md
  - User Requirements:
    - user-requirements.md
  - Data Schemas:
    - building_inventories.md